name: 'Test'

on:
  push:
    branches-ignore:
      - 'wip/*'
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - 'ubuntu-latest'
        - 'macos-latest'
        - 'windows-latest'
    steps:
      # Check out; action built on dev machine to `dist/index.js`!
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      # Run it like we would in the wild:
      - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1
        with:
          ruby-version: 2.7

      - name: Set up asciidoctor
        uses: ./

      - name: Test
        run: ruby test/run_tests.rb
